### ISSUE TITLE
Can I pickle WordInfoList?

### ISSUE THREAD

**Issue by knok** [WorksApplications/SudachiPy#113]
I'm trying to use spaCy/GiNZA with pickle.
Now dartsclone supports pickle, but still problem is there.
In my case, sudachipy.dictionarylib.wordinfolist.WordInfoList object has mmap.mmap object and it didn't support pickle.
Is there a way to prevent it?

**Comment by sorami** [comment]
Hello @knok !

Could you show me your code for the pickle serialization, and the corresponding error about the mmap?

The current SudachiPy code uses mmap when loading the binary dictionary (e.g., `dictionarylib.BinaryDictionary`), and we do not have an alternative way to load dictionaries without mmap at the moment. It may take some time to change the structure to allow such cases.

@izziiyt , do you have any comments on this topic?

c.f. Janome has an option to enable/disable mmap; [janome package — Janome API reference v0.3](https://mocobeta.github.io/janome/api/janome.html#janome.tokenizer.Tokenizer)

**Comment by izziiyt** [comment]
@sorami 

> Could you show me your code for the pickle serialization, and the corresponding error about the mmap?

I want too.

@knok 
Could you share us the error message and some references from which you know mmap.mmap isn't supported by pickle ?

**Comment by izziiyt** [comment]
My guess is that "mmap.mmap isn't supported by pickle" is wrong and "file object in memory using mmap.mmap isn't supported" is correct. If so, we have 2 options (either or both)

1.  mmap.mmap disable option
2.  dicrionary less tokenizer instance available and possible to set dictionary in use (after decode pickle)

Applying 1st approach, users like @knok can make fat pickle including model & dictionary. 
Applying 2nd approach, users like @knok can make pickle including just a model and can set dictionary in use.

This idea stands on my guess. I'd like to discuss after the problem gets more clear.

**Comment by knok** [comment]
Thank you for your response. The reproduce code is the following:
```
import pickle
import spacy
nlp = spacy.load("ja_ginza")
text = 'イラン反政府デモ続く　反米で「団結」、ウクライナ機誤射で一転'
doc = nlp(text)
with open("doc.pkl", "wb") as f:
    pickle.dump(doc, f)
```
It causes the following exception:
```
Traceback (most recent call last):
  File "/home/knok/nlp/dataset/morningstar/tmp.py", line 9, in <module>
    pickle.dump(doc, f)
  File "doc.pyx", line 1256, in spacy.tokens.doc.pickle_doc
  File "/opt/p3/lib/python3.7/site-packages/srsly/_pickle_api.py", line 14, in pickle_dumps
    return cloudpickle.dumps(data, protocol=protocol)
  File "/opt/p3/lib/python3.7/site-packages/srsly/cloudpickle/cloudpickle.py", line 1125, in dumps
    cp.dump(obj)
  File "/opt/p3/lib/python3.7/site-packages/srsly/cloudpickle/cloudpickle.py", line 482, in dump
    return Pickler.dump(self, obj)
  File "/usr/lib/python3.7/pickle.py", line 437, in dump
    self.save(obj)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/pickle.py", line 786, in save_tuple
    save(element)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.7/pickle.py", line 882, in _batch_setitems
    save(v)
  File "/usr/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.7/pickle.py", line 882, in _batch_setitems
    save(v)
  File "/usr/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.7/pickle.py", line 882, in _batch_setitems
    save(v)
  File "/usr/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.7/pickle.py", line 882, in _batch_setitems
    save(v)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/pickle.py", line 816, in save_list
    self._batch_appends(obj)
  File "/usr/lib/python3.7/pickle.py", line 843, in _batch_appends
    save(tmp[0])
  File "/usr/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.7/pickle.py", line 882, in _batch_setitems
    save(v)
  File "/usr/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.7/pickle.py", line 882, in _batch_setitems
    save(v)
  File "/usr/lib/python3.7/pickle.py", line 524, in save
    rv = reduce(self.proto)
TypeError: can't pickle mmap.mmap objects
```

**Comment by sorami** [comment]
Thank you for sharing the code and the error, @knok . I can reproduce the error on my side.

***

I was briefly looking at the spaCy document.

It seems more appropriate to spaCy's `Doc.to_bytes` and `Doc.from_bytes` methods for serialization; [Doc · spaCy API Documentation](https://spacy.io/api/doc#to_bytes)

Trying the `to_bytes` methods on a GiNZA doc, I get the following error;
```
import spacy
nlp_ja = spacy.load("ja_ginza")
doc_ja = nlp_ja("銀座でランチ")
doc_ja.to_bytes()
```

```
TypeError: can not serialize 'Morpheme' object
```

**Comment by hiroshi-matsuda-rit** [comment]
@sorami I'd like to try to solve the serialization error of class objects of GiNZA.

**Comment by hiroshi-matsuda-rit** [comment]
@knok @sorami @izziiyt I'd like to avoid serialization errors by skipping to set Morpheme instances to `token._.sudachi` until setting `nlp.tokenizer.set_enable_ex_sudachi(True)`.
Please see the description in my feature branch below.
https://github.com/megagonlabs/ginza/tree/feature/enable_ex_sudachi#ginza-311

**Comment by hiroshi-matsuda-rit** [comment]
I just released GiNZA v3.1.1 with above refinement.
Thank so much!

**Comment by sorami** [comment]
@hiroshi-matsuda 
Awesome, thank you for the GiNZA update!

I confirmed that the serialization for both the sample code @knok provided, and the sample code on the GiNZA readme works without a problem.

```
$ pip install -U ginza
$ pip show ginza
Name: ginza
Version: 3.1.1
...
```

```
import pickle
import spacy
nlp = spacy.load("ja_ginza")
text = 'イラン反政府デモ続く　反米で「団結」、ウクライナ機誤射で一転'
doc = nlp(text)
with open("doc.pkl", "wb") as f:
    pickle.dump(doc, f)
```

```
import spacy
import pickle
nlp = spacy.load('ja_ginza')
doc1 = nlp('This example will be serialized correctly.')
doc1.to_bytes()
with open('sample1.pickle', 'wb') as f:
    pickle.dump(doc1, f)
```

**Comment by sorami** [comment]
I believe the issue @knok raised initially, which is to use spaCy/GiNZA with pickle, is resolved now thanks to @hiroshi-matsuda-rit .

I close this issue.
