### ISSUE TITLE
dictionarylib not found

### ISSUE THREAD

**Issue by daisukelab** [WorksApplications/SudachiPy#15]
Hi, I tried and got following error. 
Is there anything needed to install?
Thank you.

```
$ sudachipy
Traceback (most recent call last):
  File "/home/xxxx/.pyenv/versions/anaconda3-5.1.0/bin/sudachipy", line 7, in <module>
    from sudachipy.command_line import main
  File "/home/xxxx/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/sudachipy/__init__.py", line 2, in <module>
    from . import tokenizer
  File "/home/xxxx/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/sudachipy/tokenizer.py", line 3, in <module>
    from . import lattice
  File "/home/xxxx/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/sudachipy/lattice.py", line 2, in <module>
    from . import dictionarylib
ImportError: cannot import name 'dictionarylib'
```

**Comment by mana-ysh** [comment]
Hi @daisukelab

> Is there anything needed to install?

You need to get the binary dictionary file and put it under `resources` directory, as well as getting the source code.
And I recommend to use the following commands to install now.
```
$ git clone https://github.com/WorksApplications/SudachiPy.git
$ cd SudachiPy
$ pip install -e .
$ cd resources
$ wget https://github.com/WorksApplications/Sudachi/releases/download/v0.1.0/sudachi-0.1.0-dictionary-core.zip && unzip sudachi-0.1.0-dictionary-core.zip
$ mv system_core.dic system.dic
```
If you want to use `dictionary-full`, which has more morphemes, please download `sudachi-0.1.0-dictionary-full.zip` version.

**Comment by fhudi** [comment]
> $ git clone https://github.com/WorksApplications/SudachiPy.git
> $ cd SudachiPy
> $ pip install -e .

Hi @daisukelab @mana-ysh 
You can use the following syntax to skip cloning the repo manually
`pip install -e git+git://github.com/WorksApplications/SudachiPy@develop#egg=SudachiPy`

Currently installation can only be done in develop mode for SudachiPy.
Sorry for inconvenience caused.

> $ cd resources
> $ wget https://github.com/WorksApplications/Sudachi/releases/download/v0.1.0/sudachi-0.1.0-dictionary-core.zip && unzip sudachi-0.1.0-dictionary-core.zip
> $ mv system_core.dic system.dic

Also currently dictionary is put under SudachiPy Folder (SudachiPy/resources/system.dic), which is not the case for (Java) Sudachi. This might be supported in the future so that Sudachi and SudachiPy can share dictionary, as indirectly mentioned on [Issue #4](4).

As for now please follow @mana-ysh suggestion.

**Comment by daisukelab** [comment]
@kazuma-t I'm sorry but issue is still there...

Thank you for your support, but it still doesn't work. Here's what have tried.

1. Following not-cloning procedure.
```sh
(anaconda3-5.1.0) xxxxx@ubuntu1604:~/lab/ext$ pip install -e git+git://github.com/WorksApplications/SudachiPy@develop#egg=SudachiPy
   :
Successfully installed SudachiPy
(anaconda3-5.1.0) xxxxx@ubuntu1604:~/lab/ext$ ls
opencv-3.4.0
```
--> Problem 1: No SudachiPy/resources folder made.

2. Clone repo.
```sh
(anaconda3-5.1.0) xxxxx@ubuntu1604:~/lab/ext$ git clone https://github.com/WorksApplications/SudachiPy.git
Cloning into 'SudachiPy'...
remote: Enumerating objects: 30, done.
remote: Counting objects: 100% (30/30), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 458 (delta 16), reused 16 (delta 9), pack-reused 428
Receiving objects: 100% (458/458), 88.58 KiB | 0 bytes/s, done.
Resolving deltas: 100% (277/277), done.
Checking connectivity... done.
(anaconda3-5.1.0) xxxxx@ubuntu1604:~/lab/ext$ cd SudachiPy/resources/
(anaconda3-5.1.0) xxxxx@ubuntu1604:~/lab/ext/SudachiPy/resources$ wget https://github.com/WorksApplications/Sudachi/releases/download/v0.1.0/sudachi-0.1.0-dictionary-core.zip && unzip sudachi-0.1.0-dictionary-core.zip
   :
  inflating: system_core.dic         
(anaconda3-5.1.0) xxxxx@ubuntu1604:~/lab/ext/SudachiPy/resources$ ls
char.def  rewrite.def  sudachi-0.1.0-dictionary-core.zip  sudachi.json  system_core.dic  unk.def
(anaconda3-5.1.0) xxxxx@ubuntu1604:~/lab/ext/SudachiPy/resources$ mv system_core.dic system.dic 
(anaconda3-5.1.0) xxxxx@ubuntu1604:~/lab/ext/SudachiPy/resources$ sudachipy 
Traceback (most recent call last):
  File "/home/xxxxx/.pyenv/versions/anaconda3-5.1.0/bin/sudachipy", line 11, in <module>
    load_entry_point('SudachiPy', 'console_scripts', 'sudachipy')()
  File "/home/xxxxx/lab/ext/src/sudachipy/sudachipy/command_line.py", line 60, in main
    dict_ = dictionary.Dictionary(settings)
  File "/home/xxxxx/lab/ext/src/sudachipy/sudachipy/dictionary.py", line 24, in __init__
    self.read_system_dictionary(os.path.join(config.RESOURCEDIR, settings["systemDict"]))
  File "/home/xxxxx/lab/ext/src/sudachipy/sudachipy/dictionary.py", line 60, in read_system_dictionary
    with open(filename, 'r+b') as system_dic:
FileNotFoundError: [Errno 2] No such file or directory: '/home/xxxxx/lab/ext/src/sudachipy/sudachipy/../resources/system.dic'
```

--> Problem 2: Dictionary still not found

3. Wrong folder name? rename then...
```sh
(anaconda3-5.1.0) xxxxx@ubuntu1604:~/lab/ext/SudachiPy/resources$ cd ../..
(anaconda3-5.1.0) xxxxx@ubuntu1604:~/lab/ext$ mv SudachiPy sudachipy
(anaconda3-5.1.0) xxxxx@ubuntu1604:~/lab/ext$ sudachipy
  :
FileNotFoundError: [Errno 2] No such file or directory: '/home/xxxxx/lab/ext/src/sudachipy/sudachipy/../resources/system.dic'
```
--> Same thing

4. Redo renaming, then install from cloned repo.
```sh
(anaconda3-5.1.0) xxxxx@ubuntu1604:~/lab/ext$ pip uninstall sudachipy
  :
(anaconda3-5.1.0) xxxxx@ubuntu1604:~/lab/ext$ mv sudachipy SudachiPy
(anaconda3-5.1.0) xxxxx@ubuntu1604:~/lab/ext$ cd SudachiPy/
(anaconda3-5.1.0) xxxxx@ubuntu1604:~/lab/ext/SudachiPy$ pip install .
  :
(anaconda3-5.1.0) xxxxx@ubuntu1604:~/lab/ext/SudachiPy$ sudachipy
Traceback (most recent call last):
  File "/home/xxxxx/.pyenv/versions/anaconda3-5.1.0/bin/sudachipy", line 7, in <module>
    from sudachipy.command_line import main
  File "/home/xxxxx/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/sudachipy/__init__.py", line 2, in <module>
    from . import tokenizer
  File "/home/xxxxx/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/sudachipy/tokenizer.py", line 3, in <module>
    from . import lattice
  File "/home/xxxxx/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/sudachipy/lattice.py", line 2, in <module>
    from . import dictionarylib
ImportError: cannot import name 'dictionarylib'
```
--> Problem 3: Come back to the original issue...

**Comment by fhudi** [comment]
@daisukelab 

> --> Problem 1: No SudachiPy/resources folder made.
> --> Problem 2: Dictionary still not found
> --> Same thing

This is the aforementioned problem, [Issues #4 dictionary file management structure](4).

> --> Problem 3: Come back to the original issue...

Should use `-e` flag during installation. i.e. `pip install -e .`

For the complete syntax please follows @mana-ysh suggestion.
```
$ git clone https://github.com/WorksApplications/SudachiPy.git
$ cd SudachiPy
$ pip install -e .
$ cd resources
$ wget https://github.com/WorksApplications/Sudachi/releases/download/v0.1.0/sudachi-0.1.0-dictionary-core.zip && unzip sudachi-0.1.0-dictionary-core.zip
$ mv system_core.dic system.dic
```

**Comment by daisukelab** [comment]
Thank you, now issue have gone... This resolved issue.

```sh
$ pip install -e .
```

Thank you all for quick support!
