### ISSUE TITLE
sudachipy command line not working with -a option

### ISSUE THREAD

**Issue by hiroshi-matsuda-rit** [WorksApplications/SudachiPy#150]
```console
$ sudachipy -a
テストする。
Traceback (most recent call last):
  File "/mnt/c/git/ginza/venv.wsl/bin/sudachipy", line 33, in <module>
    sys.exit(load_entry_point('SudachiPy==0.5.0', 'console_scripts', 'sudachipy')())
  File "/mnt/c/git/ginza/venv.wsl/lib/python3.9/site-packages/sudachipy/command_line.py", line 237, in main
    args.handler(args, args.print_usage)
  File "/mnt/c/git/ginza/venv.wsl/lib/python3.9/site-packages/sudachipy/command_line.py", line 175, in _command_tokenize
    run(tokenizer_obj, mode, input_, print_all, stdout_logger, enable_dump)
  File "/mnt/c/git/ginza/venv.wsl/lib/python3.9/site-packages/sudachipy/command_line.py", line 73, in run
    '[{}]'.format(','.join([str(synonym_group_id) for synonym_group_id in m.synonym_group_ids]))]
TypeError: 'method' object is not iterable
```
SudachiPy==0.5.0
SudachiDict-core==20201223.post1
Python 3.9.1
WSL2 Ubuntu 20.04

**Comment by t-yamamura** [comment]
@hiroshi-matsuda-rit 
Thank you for the report.

We have released a new version [v0.5.1](https://github.com/WorksApplications/SudachiPy/releases/tag/v0.5.1) to fix this issue.
