### ISSUE TITLE
v0.3.2 Install fails on Windows

### ISSUE THREAD

**Issue by hiroshi-matsuda-rit** [WorksApplications/SudachiPy#53]
Unfortunately, encoding problem was happened on Windows while installing v0.3.2.
```
        long_description=open('README.md').read(),
```
This is the log from spaCy's CI test environment.
```
##[section]Starting: Install dependencies
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.151.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
========================== Starting Command Output ===========================
##[command]"C:\windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "d:\a\_temp\3c6304a3-b77d-4d3f-9537-ed92905ea38d.cmd""
Collecting pip==18.1
  Downloading https://files.pythonhosted.org/packages/c2/d7/90f34cb0d83a6c5631cf71dfe64cc1054598c843a92b400e55675cc2ac37/pip-18.1-py2.py3-none-any.whl (1.3MB)
Installing collected packages: pip
  Found existing installation: pip 19.1.1
    Uninstalling pip-19.1.1:
      Successfully uninstalled pip-19.1.1
Successfully installed pip-18.1
Ignoring pathlib: markers 'python_version < "3.4"' don't match your environment
Collecting https://github.com/megagonlabs/ginza/releases/download/v2.0.0/SudachiPy-0.3.2-python27.tar.gz (from -r requirements.txt (line 24))
  Downloading https://github.com/megagonlabs/ginza/releases/download/v2.0.0/SudachiPy-0.3.2-python27.tar.gz (44kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-req-build-ebs0tm0p\setup.py", line 7, in <module>
        long_description=open('README.md').read(),
      File "c:\hostedtoolcache\windows\python\3.5.4\x64\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 4011: character maps to <undefined>
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\VSSADM~1\AppData\Local\Temp\pip-req-build-ebs0tm0p\
You are using pip version 18.1, however version 19.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
##[error]Cmd.exe exited with code '1'.
##[section]Finishing: Install dependencies
```

**Comment by izziiyt** [comment]
It looks the problem is caused from encoding matter.  
I think specifying encoding solves this problem.
```
long_description=open('README.md', encoding='utf-8').read()](url)
```
(I haven't tried and I don't have time just now. )

**Comment by izziiyt** [comment]
`v0.3.3` solves this issue
