### ISSUE TITLE
Failed to install the dictionary on Windows

### ISSUE THREAD

**Issue by BLKSerene** [WorksApplications/SudachiPy#87]
Hi, I'm trying to install the built dictionary for Python following instructions in doc, but the installation failed. The same happens for the core dictionary, so is there anything that I've missed?

OS: Windows 10 64-bit
Python: 3.7.4 64-bit

```
pip install SudachiDict_full-20190718.tar.gz
Processing sudachidict_full-20190718.tar.gz
ERROR: Exception:
Traceback (most recent call last):
  File "d:\python\lib\site-packages\pip\_internal\cli\base_command.py", line 188, in main
    status = self.run(options, args)
  File "d:\python\lib\site-packages\pip\_internal\commands\install.py", line 345, in run
    resolver.resolve(requirement_set)
  File "d:\python\lib\site-packages\pip\_internal\legacy_resolve.py", line 196, in resolve
    self._resolve_one(requirement_set, req)
  File "d:\python\lib\site-packages\pip\_internal\legacy_resolve.py", line 359, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "d:\python\lib\site-packages\pip\_internal\legacy_resolve.py", line 307, in _get_abstract_dist_for
    self.require_hashes
  File "d:\python\lib\site-packages\pip\_internal\operations\prepare.py", line 199, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "d:\python\lib\site-packages\pip\_internal\download.py", line 1051, in unpack_url
    unpack_file_url(link, location, download_dir, hashes=hashes)
  File "d:\python\lib\site-packages\pip\_internal\download.py", line 985, in unpack_file_url
    unpack_file(from_path, location, content_type, link)
  File "d:\python\lib\site-packages\pip\_internal\utils\misc.py", line 741, in unpack_file
    untar_file(filename, location)
  File "d:\python\lib\site-packages\pip\_internal\utils\misc.py", line 672, in untar_file
    member.name for member in tar.getmembers()
  File "d:\python\lib\tarfile.py", line 1763, in getmembers
    self._load()        # all members, we first have to
  File "d:\python\lib\tarfile.py", line 2350, in _load
    tarinfo = self.next()
  File "d:\python\lib\tarfile.py", line 2281, in next
    self.fileobj.seek(self.offset - 1)
  File "d:\python\lib\gzip.py", line 368, in seek
    return self._buffer.seek(offset, whence)
  File "d:\python\lib\_compression.py", line 143, in seek
    data = self.read(min(io.DEFAULT_BUFFER_SIZE, offset))
  File "d:\python\lib\gzip.py", line 471, in read
    uncompress = self._decompressor.decompress(buf, size)
zlib.error: Error -3 while decompressing data: invalid code lengths set
```

**Comment by fhudi** [comment]
Hi, I could not reproduce this. Tried on python 3.5.4 64 bit, Windows 10 64-bit command prompt.
Have you tried to re-download the SudachiDict file?

![image](https://user-images.githubusercontent.com/6541786/63587817-de54f780-c5df-11e9-8d60-62595a3636c1.png)

**Comment by BLKSerene** [comment]
That's weird, it does work after re-downloading the dictionary. There might be some problems with my internet connections. Anyway, thanks!
